// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Cover letter generation flow.
 *
 * - generateCoverLetter - A function that generates a cover letter.
 * - CoverLetterInput - The input type for the generateCoverLetter function.
 * - CoverLetterOutput - The return type for the generateCoverLetter function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CoverLetterInputSchema = z.object({
  personalInformation: z.object({
    name: z.string().describe('Your full name.'),
    email: z.string().email().describe('Your email address.'),
    phone: z.string().describe('Your phone number.'),
    address: z.string().describe('Your address.'),
  }).describe('Your personal information.'),
  recipientInformation: z.object({
    company: z.string().describe('The company name.'),
    contactName: z.string().optional().describe('The recipient name (if known).'),
    address: z.string().describe('The recipient address.'),
  }).describe('The recipient information.'),
  jobDetails: z.object({
    jobTitle: z.string().describe('The job title.'),
    jobDescription: z.string().describe('The job description.'),
    relevantSkills: z.string().describe('Relevant skills for the job.'),
    experienceSummary: z.string().describe('Summary of work experience.'),
  }).describe('The job details.'),
  tone: z.string().optional().describe('The tone of the cover letter (e.g., formal, informal, enthusiastic).'),
  templateStyle: z.string().optional().describe('The template style to apply to the cover letter.'),
});
export type CoverLetterInput = z.infer<typeof CoverLetterInputSchema>;

const CoverLetterOutputSchema = z.object({
  coverLetter: z.string().describe('The generated cover letter.'),
});
export type CoverLetterOutput = z.infer<typeof CoverLetterOutputSchema>;

export async function generateCoverLetter(input: CoverLetterInput): Promise<CoverLetterOutput> {
  return generateCoverLetterFlow(input);
}

const prompt = ai.definePrompt({
  name: 'coverLetterPrompt',
  input: {schema: CoverLetterInputSchema},
  output: {schema: CoverLetterOutputSchema},
  prompt: `You are an expert cover letter writer. Your task is to create a compelling, professional, and human-sounding cover letter based on the information below.

IMPORTANT: Avoid repeating the job title or company name excessively. Use varied and natural language. The letter should flow smoothly and not sound like a template.

Personal Information:
Name: {{{personalInformation.name}}}
Email: {{{personalInformation.email}}}
Phone: {{{personalInformation.phone}}}
Address: {{{personalInformation.address}}}

Recipient Information:
Company: {{{recipientInformation.company}}}
{{#if recipientInformation.contactName}}
Contact Name: {{{recipientInformation.contactName}}}
{{/if}}
Address: {{{recipientInformation.address}}}

Job Details:
Job Title: {{{jobDetails.jobTitle}}}
Job Description: {{{jobDetails.jobDescription}}}
Relevant Skills: {{{jobDetails.relevantSkills}}}
Experience Summary: {{{jobDetails.experienceSummary}}}

{{#if tone}}
Tone: {{{tone}}}
{{/if}}

{{#if templateStyle}}
Template Style: {{{templateStyle}}}
{{/if}}

Craft a cover letter that is tailored to the job description. Highlight the most relevant skills and achievements from the experience summary. Ensure the letter is optimized for Applicant Tracking Systems (ATS) by naturally incorporating keywords from the job description, but prioritize making it sound authentic and human-written.

If a hiring manager's name is not provided, use a generic but professional salutation like "Dear Hiring Team,".
`,
});

const generateCoverLetterFlow = ai.defineFlow(
  {
    name: 'generateCoverLetterFlow',
    inputSchema: CoverLetterInputSchema,
    outputSchema: CoverLetterOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
