// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Cover letter generation flow.
 *
 * - generateCoverLetter - A function that generates a cover letter.
 * - CoverLetterInput - The input type for the generateCoverLetter function.
 * - CoverLetterOutput - The return type for the generateCoverLetter function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CoverLetterInputSchema = z.object({
  personalInformation: z.object({
    name: z.string().describe('Your full name.'),
    email: z.string().email().describe('Your email address.'),
    phone: z.string().describe('Your phone number.'),
    address: z.string().describe('Your address.'),
  }).describe('Your personal information.'),
  recipientInformation: z.object({
    company: z.string().describe('The company name.'),
    contactName: z.string().describe('The recipient name (if known).'),
    address: z.string().describe('The recipient address.'),
  }).describe('The recipient information.'),
  jobDetails: z.object({
    jobTitle: z.string().describe('The job title.'),
    jobDescription: z.string().describe('The job description.'),
    relevantSkills: z.string().describe('Relevant skills for the job.'),
    experienceSummary: z.string().describe('Summary of work experience.'),
  }).describe('The job details.'),
  tone: z.string().optional().describe('The tone of the cover letter (e.g., formal, informal, enthusiastic).'),
  templateStyle: z.string().optional().describe('The template style to apply to the cover letter.'),
});
export type CoverLetterInput = z.infer<typeof CoverLetterInputSchema>;

const CoverLetterOutputSchema = z.object({
  coverLetter: z.string().describe('The generated cover letter.'),
});
export type CoverLetterOutput = z.infer<typeof CoverLetterOutputSchema>;

export async function generateCoverLetter(input: CoverLetterInput): Promise<CoverLetterOutput> {
  return generateCoverLetterFlow(input);
}

const prompt = ai.definePrompt({
  name: 'coverLetterPrompt',
  input: {schema: CoverLetterInputSchema},
  output: {schema: CoverLetterOutputSchema},
  prompt: `You are a professional cover letter writer. Generate a cover letter based on the provided information.

Personal Information:
Name: {{{personalInformation.name}}}
Email: {{{personalInformation.email}}}
Phone: {{{personalInformation.phone}}}
Address: {{{personalInformation.address}}}

Recipient Information:
Company: {{{recipientInformation.company}}}
Contact Name: {{{recipientInformation.contactName}}}
Address: {{{recipientInformation.address}}}

Job Details:
Job Title: {{{jobDetails.jobTitle}}}
Job Description: {{{jobDetails.jobDescription}}}
Relevant Skills: {{{jobDetails.relevantSkills}}}
Experience Summary: {{{jobDetails.experienceSummary}}}


{{#if tone}}
Tone: {{{tone}}}
{{/if}}

{{#if templateStyle}}
Template Style: {{{templateStyle}}}
{{/if}}

Write a compelling cover letter tailored to the job description, highlighting key achievements and skills. Optimize the cover letter for Applicant Tracking Systems (ATS) by incorporating relevant keywords from the job description.
`,  
});

const generateCoverLetterFlow = ai.defineFlow(
  {
    name: 'generateCoverLetterFlow',
    inputSchema: CoverLetterInputSchema,
    outputSchema: CoverLetterOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
